version: 2

builds:
  - id: emu
    binary: emu
    main: ./cmd/emu
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: emu
    name_template: "emu_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    builds:
      - emu
    files:
      - LICENSE
      - README.md
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip

changelog:
  disable: true

brews:
  - name: emu
    ids:
      - emu
    repository:
      owner: bartekpacia
      name: homebrew-tools
    directory: Formula
    homepage: https://github.com/bartekpacia/emu
    description: Handy mini-CLI for more pleasant work with Android Emulator
    license: MIT
    install: |
      man_content = `./emu docs --format man-with-section`
      File.write("emu.1", man_content)

      bin.install "emu"
      man1.install "emu.1"
      generate_completions_from_executable(bin/"emu", "completion")

aurs:
  - name: emu-bin
    ids:
      - emu
    homepage: https://github.com/bartekpacia/emu
    description: Handy mini-CLI for more pleasant work with Android Emulator
    maintainers:
      - Bartek Pacia <barpac02@gmail.com>
    private_key: "{{ .Env.AUR_SSH_PRIVATE_KEY }}"
    git_url: git@github.com:bartekpacia/aur.git
    directory: emu-bin
    package: |
      cd "$pkgname-$pkgver"
      # bin
      install -Dm755 emu "${pkgdir}/usr/bin/emu"

      # license
      install -Dm644 LICENSE "${pkgdir}/usr/share/licenses/emu/LICENSE"

      # completions
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      # TODO: use completion scripts from executable
      install -Dm755 autocomplete/bash_autocomplete "${pkgdir}/usr/share/bash-completion/completions/emu"
      install -Dm755 autocomplete/zsh_autocomplete "${pkgdir}/usr/share/zsh/site-functions/_emu"

      # man pages
      # install -Dm644 "./manpages/mybin.1.gz" "${pkgdir}/usr/share/man/man1/mybin.1.gz"
