builds:
  - id: emu
    binary: emu
    main: ./cmd/emu
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: emu
    name_template: 'emu_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    builds:
      - emu
    files:
      - LICENSE
      - README.md
      - autocomplete/zsh_autocomplete
      - autocomplete/bash_autocomplete
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip

changelog:
  skip: true

brews:
  - name: emu
    ids:
      - emu
    repository:
      owner: bartekpacia
      name: homebrew-tools
    folder: Formula
    homepage: https://github.com/bartekpacia/emu
    description: Handy mini-CLI for more pleasant work with Android Emulator.
    license: MIT
    install: |
      bin.install "emu"
      bash_completion.install "autocomplete/bash_autocomplete" => "emu"
      zsh_completion.install "autocomplete/zsh_autocomplete" => "_emu"
